changes:
weaponsforge/my-phonebook pull request #133
Opened 2023-05-01 06:49 UTC by vikyw89

when visiting / 

- signed in user will be redirected to contacts/ 
- unsigned in user will be redirected to login/

when visiting login 
- signed in user will be redirected to contacts/

2023-05-01 10:56 UTC, weaponsforge commented on client/src/pages/index.js
> +  })
Looks good, but I found a few inconsistencies for the case:

> when visiting /
> - signed in user will be redirected to contacts/

Please view the attached video and take note of the multiple redirects on the URL (URL route goes from "/" to "/login" and finally, "/contacts"), and the red-letter warnings on the chrome dev console.

### Video: Multiple Redirection and Chrome Dev Warnings

https://user-images.githubusercontent.com/56998001/235442888-9adff0da-13e5-4e9b-903b-d8dd6df362ed.mp4

---

### Suggestions

Here are some suggestions but please confirm and verify if it's effective:

Listen for the `auth.authLoading` status in the deps array and call `router.push` only after `auth.authLoading` becomes `false`.

```
  useEffect(()=>{
    if (!auth.authLoading) {
      if (auth.authUser) {
        router.push('/contacts')
      } else {
        router.push('/login')
      }
    }
  }, [auth])
```

2023-05-01 16:52 UTC, weaponsforge requested changes

2023-05-01 16:52 UTC, weaponsforge commented on client/src/pages/index.js
> +  })
Looks good, but I found a few inconsistencies for the case:

> when visiting /
> - signed in user will be redirected to contacts/

Please view the attached videos (taken while running this branch) and take note of the multiple redirects (URL route goes from "/" to "/login" and finally, "/contacts"), and the red-letter warnings on the chrome dev console.

### Video: Multiple Redirection and Chrome Dev Warnings

When visiting "/" while signed in

https://user-images.githubusercontent.com/56998001/235442888-9adff0da-13e5-4e9b-903b-d8dd6df362ed.mp4

### Video: Chrome Dev Warnings

When visiting "/" while signed-out

https://user-images.githubusercontent.com/56998001/235443795-9e687fbb-e0ae-41da-a959-c6a611e9de9f.mp4

---

### Suggestions

Here are some suggestions to minimize the mentioned bugs and warnings but please confirm and verify if it's effective:

Listen for the `auth.authLoading` status in the deps array and call `router.push` only after `auth.authLoading` becomes `false`.

```
  useEffect(()=>{
    if (!auth.authLoading) {
      if (auth.authUser) {
        router.push('/contacts')
      } else {
        router.push('/login')
      }
    }
  }, [auth])
```

2023-05-02 04:52 UTC, vikyw89 commented on client/src/pages/index.js
> +  })
file:///home/vikyw/Downloads/Screencast%20from%202023-05-02%2012-45-27.mp4

2023-05-02 06:49 UTC, weaponsforge commented on client/src/pages/index.js
> +  })
Thanks for the updates! I re-run the branch and verified that the multiple redirects and mentioned console errors are fixed.

I would like to note one small thing, which I will mention in a separate comment. This PR is ready to merge after confirming this item.

2023-05-02 07:02 UTC, weaponsforge requested changes

2023-05-02 07:02 UTC, weaponsforge commented on client/src/common/ui/loadingLinear/index.js
> +  const authLoading = useSyncV('auth.loading')
Currently, we do not have an `auth.loading` use-sync-v store field value. Using it like this always assigns an `undefined` value to the `authLoading` variable.

Kindly see the use-sync-v `auth` store fields definition in the `/client/src/lib/store/index.js`. If you meant to listen for the Firebase Auth "loading" status, pls use `auth.authLoading`.

#### P.S. You can rename

`auth.authLoading` => `auth.loading` if this sounds more consistent, but please be sure to update all `auth.authLoading` references in the codes.

2023-05-02 08:28 UTC, weaponsforge approved these changes

2023-05-02 08:29 UTC, merged